version: '3.8'

services:
  web:
    image: nginx:1.14.2
    container_name: web_app
    ports:
      - "8087:80"
    volumes:
      - ./files/index.html:/usr/share/nginx/html/index.html
    restart: unless-stopped
